In [302]:
import pandas as pd

df = pd.read_excel('./data/hosp-epis-stat-admi-diag-2012-13-tab.xlsx', sheet_name="Primary diagnosis - 3 char", skiprows=18)

df = df.iloc[2:].reset_index(drop=True)
df = df.rename(columns={"Unnamed: 0": "Code"})

df.head()

,Code,Primary diagnosis: 3 character code and description,Finished consultant episodes,Admissions,Male,Female,Gender unknown,Emergency,Waiting list,Planned,...,Age 55-59,Age 60-64,Age 65-69,Age 70-74,Age 75-79,Age 80-84,Age 85-89,Age 90+,Day case,FCE Bed Days
0,A00,Cholera ...,11.0,10.0,7,4.0,0,7.0,2.0,0,...,0,0.0,0.0,0,0.0,0.0,2.0,0,2.0,26.0
1,A01,Typhoid and paratyphoid fevers ...,429.0,270.0,227,202.0,0,240.0,9.0,15,...,12,32.0,13.0,2,0.0,0.0,0.0,0,17.0,1552.0
2,A02,Other salmonella infections ...,930.0,564.0,452,478.0,0,537.0,11.0,8,...,47,38.0,68.0,63,60.0,59.0,34.0,13,12.0,4380.0
3,A03,Shigellosis ...,167.0,97.0,102,65.0,0,95.0,1.0,1,...,5,13.0,5.0,10,4.0,6.0,0.0,2,2.0,577.0
4,A04,Other bacterial intestinal infections ...,18416.0,10273.0,7912,10504.0,0,6963.0,2724.0,411,...,929,1040.0,1417.0,1646,1881.0,2608.0,2108.0,1418,2976.0,125159.0

In [303]:
df.columns = df.columns.str.strip()
df.columns

Index(['Code', 'Primary diagnosis: 3 character code and description',
       'Finished consultant episodes', 'Admissions', 'Male', 'Female',
       'Gender unknown', 'Emergency', 'Waiting list', 'Planned',
       'Other admission method', 'Mean time waited', 'Median time waited',
       'Mean length of stay', 'Median length of stay', 'Mean age', 'Age 0',
       'Age 1-4', 'Age 5-9', 'Age 10-14', 'Age 15', 'Age 16', 'Age 17',
       'Age 18', 'Age 19', 'Age 20-24', 'Age 25-29', 'Age 30-34', 'Age 35-39',
       'Age 40-44', 'Age 45-49', 'Age 50-54', 'Age 55-59', 'Age 60-64',
       'Age 65-69', 'Age 70-74', 'Age 75-79', 'Age 80-84', 'Age 85-89',
       'Age 90+', 'Day case', 'FCE Bed Days'],
      dtype='object')

In [304]:
df_emergency = df[['Code','Primary diagnosis: 3 character code and description','Emergency']]
df_emergency = df_emergency.dropna()
df_emergency

     Code Primary diagnosis: 3 character code and description  Emergency
0     A00  Cholera                                       ...         7.0
1     A01  Typhoid and paratyphoid fevers                ...       240.0
2     A02  Other salmonella infections                   ...       537.0
3     A03  Shigellosis                                   ...        95.0
4     A04  Other bacterial intestinal infections         ...      6963.0
...   ...                                                ...         ...
1619  Z94  Transplanted organ and tissue status          ...         0.0
1620  Z95  Presence of cardiac and vascular implants and ...         3.0
1621  Z96  Presence of other functional implants         ...        20.0
1622  Z97  Presence of other devices                     ...         1.0
1623  Z98  Other postsurgical states                     ...         0.0

[1624 rows x 3 columns]

In [333]:
def find_sheet_name(file_path, possible_names):
    xls = pd.ExcelFile(file_path)
    for name in xls.sheet_names:
        if all(k in name for k in possible_names):
            return name
    return None

In [ ]:
def find_start_row(file_path, sheet_name):
    df = pd.read_excel(file_path, sheet_name=sheet_name, header=None)
    for i, row in df.iterrows():
        row_str = ' '.join(str(cell).lower() for cell in row)
        if (
                'primary' in row_str and
                'diagnosis' in row_str and
                'emergency' in row_str
        ):
            return i
    return None

In [334]:
file_path = './data/hosp-epis-stat-admi-diag-2013-14-tab.xlsx'
sheet_name = find_sheet_name('./data/hosp-epis-stat-admi-diag-2013-14-tab.xlsx',['Primary', '3'])
print(sheet_name)
df2 = pd.read_excel('./data/hosp-epis-stat-admi-diag-2013-14-tab.xlsx',sheet_name, skiprows=17)
# df2.head()

Primary Diagnosis 3 Character
['Diagnosis Introduction', 'Primary Diagnosis Summary', 'Primary Diagnosis 3 Character', 'Primary Diagnosis 4 Character', 'All Diagnoses 3 Character', 'All Diagnoses 4 Character']